{% set name = "pyusb" %}
{% set version = "1.2.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: a4cc7404a203144754164b8b40994e2849fde1cfff06b08492f12fff9d9de7b9

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install --no-deps . -vv"

requirements:
  host:
    - pip
    - python
    - wheel
  run:
    - python

test:
  commands:
    - pip check
  imports:
    - usb
    - usb.backend
  requires:
    - pip

about:
  home: "https://pyusb.github.io/pyusb"
  license: BSD
  license_family: BSD
  license_file:
  description: |
    PyUSB offers easy USB devices communication in Python. It should work without additional code in any environment with Python >=     2.4, ctypes and an pre-built usb backend library (currently, libusb 0.1.x, libusb 1.x, and OpenUSB). 
  summary: "Python USB access module"
  doc_url: 
  dev_url: https://github.com/pyusb/pyusb

extra:

  anaconda-services:
   ref: https://anaconda.zendesk.com/agent/tickets/33492

  recipe-maintainers:
    - ianaobi
